# robot
robot_num: 10
robot_radius: 1

# map
map_width: 30
map_height: 30
obstacle_list:
  - !!python/tuple [15, 15, 1]
  - !!python/tuple [13, 16, 2]
  - !!python/tuple [13, 18, 2]
  - !!python/tuple [13, 20, 2]
  - !!python/tuple [17, 15, 2]
  - !!python/tuple [19, 15, 2]
  - !!python/tuple [5, 5, 2]
  - !!python/tuple [5, 8, 1]
  - !!python/tuple [5, 10, 1]
  - !!python/tuple [8, 5, 1]
  - !!python/tuple [10, 5, 1]

# RRT
rrt_rand_area: [0, 30]
rrt_expand_distance: 3.0
rrt_path_resolution: 0.5
rrt_goal_sample_rate: 5
rrt_max_iter: 500
rrt_play_area: [0, 30, 0, 30]

# SSSP
sampling_m: 5
expand_distance: 3
threshold_distance: 1
step_resolution: 0.5

# drawing
colors: ["cyan", "red", "green", "blue", "gold", "violet", "pink", "yellow", "purple", "hotpink"]
draw_graph: True
step_num: 5
pause_time: 0.001