# robot
<<<<<<< Updated upstream
robot_num: 5
robot_radius: 1
=======
robot_num: 2
robot_radius: 2
>>>>>>> Stashed changes

# map
map_width: 30
map_height: 20
obstacle_list:
  - !!python/tuple [20, 20, 5]
  - !!python/tuple [15, 20, 5]
  - !!python/tuple [10, 20, 5]
  - !!python/tuple [20, 5, 5]
  - !!python/tuple [15, 5, 5]
  - !!python/tuple [10, 5, 5]


# RRT
rrt_rand_area: [0, 30]
rrt_expand_distance: 3.0
rrt_path_resolution: 0.5
rrt_goal_sample_rate: 5
rrt_max_iter: 500
rrt_play_area: [0, 30, 0, 30]

# SSSP
sampling_m: 5
expand_distance: 3
threshold_distance: 1
step_resolution: 0.5
iteration: 100
edge_distance: 1.5

# drawing
colors: ["cyan", "red", "green", "blue", "gold", "violet", "pink", "yellow", "purple", "hotpink"]
draw_graph: False
step_num: 5
pause_time: 0.001